INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (1,"EO:0007001","UV-B light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (2,"EO:0007002","UV-A light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (3,"EO:0007041","antibiotic regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (4,"EO:0007049","soil environment");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (5,"EO:0007066","cytokinin regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (6,"EO:0007067","hydroponic plant culture media");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (7,"EO:0007071","suspension cell culture media");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (8,"EO:0007075","high light intensity regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (9,"EO:0007079","sulfate fertilizer regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (10,"EO:0007105","abscisic acid regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (11,"EO:0007106","Stramenopiles");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (12,"EO:0007107","Ascomycota");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (13,"EO:0007108","Proteobacteria");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (14,"EO:0007116","Hemiptera");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (15,"EO:0007128","intermittent light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (16,"EO:0007144","Pseudomonas spp.");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (17,"EO:0007149","chemical mutagen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (18,"EO:0007158","sandy soil");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (19,"EO:0007162","continuous light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (20,"EO:0007173","warm/hot temperature regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (21,"EO:0007174","cold temperature regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (22,"EO:0007175","temperature environment");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (23,"EO:0007183","herbicide regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (24,"EO:0007185","salt regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (25,"EO:0007193","day light intensity");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (26,"EO:0007199","long day length regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (27,"EO:0007200","short day length regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (28,"EO:0007203","far red light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (29,"EO:0007207","red light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (30,"EO:0007218","blue light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (31,"EO:0007221","visible light regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (32,"EO:0007233","Fungi");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (33,"EO:0007265","liquid growth media");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (34,"EO:0007266","tissue culture growth media");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (35,"EO:0007270","continuous dark (no light) regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (36,"EO:0007271","low light intensity regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (37,"EO:0007303","carbon nutrient regimen");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (38,"EO:0007373","mechanical damage");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (39,"EO:0007404","drought environment");
INSERT INTO eo (eoid,eoid_extern,eo_desc) VALUES (40,"EO:0007409","brassinosteroid");
