INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (1,"PO:0000005","cultured cell",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (2,"PO:0000006","cultured protoplast",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (3,"PO:0009046","flower",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (4,"PO:0009001","fruit",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (5,"PO:0009049","Inflorescence",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (6,"PO:0009025","leaf",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (7,"PO:0009005","root",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (8,"PO:0009010","seed",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (9,"PO:0009006","shoot",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (10,"PO:0000003","whole plant",null);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (11,"PO:0000013","cauline leaf",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (12,"PO:0000014","rosette leaf",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (13,"PO:0000037","shoot apex",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (14,"PO:0000056","Flower bud",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (15,"PO:0001016","L mature pollen stage",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (16,"PO:0001017","M germinated pollen stage",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (17,"PO:0001040","dry seed stage",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (18,"PO:0001054","4 leaf senescence stage",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (19,"PO:0001081","F mature embryo stage",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (20,"PO:0001185","C globular stage",4);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (21,"PO:0002002","peduncle",5);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (22,"PO:0004000","peduncle",5);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (23,"PO:0004507","D bilateral stage",4);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (24,"PO:0006339","juvenile leaf",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (25,"PO:0007003","IL.03 full inflorescence length reached",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (26,"PO:0007010","6 ripening",5);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (27,"PO:0007016","4 flowering",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (28,"PO:0007022","imbibition",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (29,"PO:0007036","FR.00 beginning of fruit ripening",4);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (30,"PO:0007042","5 fruit formation",4);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (31,"PO:0007049","cotyledon emergence",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (32,"PO:0007076","late rosette growth",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (33,"PO:0007078","rosette growth complete",10);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (34,"PO:0007082","LP.20 twenty or more leaves whorls visible",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (35,"PO:0007131","seedling growth",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (36,"PO:0007612","fully expanded petal",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (37,"PO:0007616","4 anthesis",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (38,"PO:0009009","Embryo",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (39,"PO:0009029","Stamen",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (40,"PO:0009030","Flower carpel",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (41,"PO:0009031","Sepals",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (42,"PO:0009032","Petals",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (43,"PO:0009047","stem",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (44,"PO:0009049","inflorescence",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (45,"PO:0009052","Pedicels",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (46,"PO:0009089","Endosperm",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (47,"PO:0020030","Cotyledon",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (48,"PO:0020038","petiole",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (49,"PO:0020040","leaf base",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (50,"PO:0020100","hypocotyl",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (51,"PO:0020127","primary root",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (52,"PO:0020137","leaf apex",6);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (53,"PO:0020142","stem internode",9);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (54,"PO:0021004","inflorescence initiation stage",10);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (55,"PO:0025281","Pollen",3);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (56,"PO:0025296","embryo radicle",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (57,"PO:0025470","Embryo cotyledon",8);
INSERT INTO po (poid,poid_extern,po_anatomy,parent_poid) VALUES (58,"PO:006345","Pollen tubes",3);
