INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (1,"Time series");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (2,"Hormone Treatment");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (3,"Compound treatment");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (4,"Organism part comparison");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (5,"Genetic modification; Development differentiation");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (6,"Abiotic stress");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (7,"Development or differentiation");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (8,"Biotic Stress");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (9,"Gene Knock Out");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (10,"Genetic modification");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (11,"Abiotic Stress, Time Series");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (12,"Time Series; Growth Condition");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (13,"Gene Knock In");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (14,"Abiotic Stress; Gene Knock In");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (15,"Abiotic Stress; Gene modification");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (16,"Growth condition");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (17,"Hormone treatment; Organism part comparison");
INSERT INTO smpl_annot_lookup (annot_id,annotation) VALUES (18,"Growth condition; Genetic modification");
